# Generated by Django 5.1.6 on 2025-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedata',
            name='working_days_in_month',
        ),
        migrations.AddField(
            model_name='homedata',
            name='operation_date',
            field=models.DateField(blank=True, null=True, verbose_name='営業日'),
        ),
    ]
